server: ":57314"
coordinator:
  addr: 'coordinator:6379'
  db: 0
  pool: 100
  read: 10s
#  blockingpoptime: 5s
gatekeeper:
  addr: 'gatekeeper:6379'
  db: 0
  pool: 100
  read: 10s
  ttl: 1h
response:
  log: "/var/log/strelka/strelka.log"
broker:
  bootstrap: "kafka:29092"
  protocol: "PLAINTEXT"
  certlocation: ""
  keylocation: ""
  calocation: ""
  topic: "analysis"
  s3redundancy: "false"

s3:
  accesskey: "S3 Access Key"
  secretkey: "S3 Secret Key"
  bucketName: "S3 bucket name"
  region: "Region that the S3 Bucket resides in"
  endpoint: "Endpoint that the S3 bucket refers to"
